from model.point_history_classifier.point_history_classifier import PointHistoryClassifier
from model.screening_clinic_hands_classifier.screening_clinic_hands_classifier import ScreeningClinicHandsClassifier
